### ISSUE TITLE
install stalls on OSX, possible due to permissions?

### ISSUE THREAD

**Issue by mike-pt** [nickpack/ansible-role-android-sdk#17] opened 2018-01-09 23:36 UTC
While running the dependencies task ansible stall forever, with -vvvv I was able to verify it is stuck running homebrew cask install and seems to be waiting for a password...

I'm guessing this would need to be run as sudo? 
 
I mostly use brew and never really used cask but I suppose it would be best not to run as root ofc.

the part where it stalls is:
```
<x.x.x.xx> ESTABLISH SSH CONNECTION FOR USER: testing
<x.x.x.xx> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=testing -o ConnectTimeout=10 -o ControlPath=/Users/user/.ansible/cp/d46427b07b -tt X.X.X.X '/bin/sh -c '"'"'/usr/bin/python /Users/testing/.ansible/tmp/ansible-tmp-1515540326.55-202654132996978/homebrew_cask.py; rm -rf "/Users/testing/.ansible/tmp/ansible-tmp-1515540326.55-202654132996978/" > /dev/null 2>&1 && sleep 0'"'"''
``` 

If I run this in my shell it does ask for a password, unless its the ssh password, but it shouldn't since `PasswordAuthentication` is set to no, and also everything else passed using the rsa key.

**Comment by nickpack** [comment] 2018-09-10 11:59
@mike-pt I am not really sure on this one, as brew cask gets run as your user and shouldnt require sudo, does `brew doctor` come back ok when run as the user you're ssh'ing in as?

**Comment by mike-pt** [comment] 2018-09-10 12:14
This was sometime ago but it was on a clean machine, fresh "factory defaults" mac mini, and at that time nope there were no issues with brew doctor.

But the intriguing part is that the log suggests its ssh that's requesting the password.

I'm installing android SDK on that box and other recently anyway so I'm not sure if this still happens, feel free to close if u can't replicate.

**Comment by nickpack** [comment] 2018-09-11 13:07
Interesting that it's SSH, not a behaviour I have seen before on an out of the box system, I am unable to reproduce so am going to close this ticket, but please do re-open if it happens again.

**Closed as completed by nickpack** 2018-09-11 13:07 UTC
